name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mahfuz4433/test-app:latest

      # - name: SSH and deploy to Digital
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker pull mahfuz4433/test-app:latest
      #       docker stop test-app
      #       docker rm test-app
      #       docker run -d --name test-app --env-file .env -p 3000:3000 mahfuz4433/test-app:latest
